# Generated by Django 2.1.7 on 2019-02-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='version_slug',
            field=models.SlugField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
