# Generated by Django 2.1.7 on 2019-02-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_license_version_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='version_slug',
            new_name='slug',
        ),
    ]
