# Generated by Django 2.1.7 on 2019-02-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0005_auto_20190216_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='details',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
