# Generated by Django 2.2.2 on 2019-06-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0006_license_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='version',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
